### ISSUE TITLE
Inconsistency between Firefox and Chrome regarding scroll bar

### ISSUE THREAD

**Issue by Nephren68** [Manotomo-Alliance-Support-Squad/coco-grad#29]
Firefox shows a scroll bar; Chrome does not. I'm just wondering what is intended (scroll bar / no scroll bar), so that the site looks consistent on both browsers.

Screenshots:
![Firefox](https://user-images.githubusercontent.com/65450159/123612224-efeb3400-d834-11eb-91f7-839b1825d654.png)
![Chrome](https://user-images.githubusercontent.com/65450159/123612297-fe395000-d834-11eb-88ec-86a3a7225697.png)

OS: Windows 10
Browsers: Firefox 89, Chrome 91

**Comment by R-Jim** [comment]
might relate to this `
::-webkit-scrollbar {
    display: none;
}
`
under messageCard.css

**Comment by Nephren68** [comment]
Yeah, I think that's it. This also happens to be related to https://github.com/Manotomo-Alliance-Support-Squad/coco-grad/issues/30 so that's gonna be fun.
