### ISSUE TITLE
Extra long word in message card causes layout to freak out

### ISSUE THREAD

**Issue by DuongTyler** [Manotomo-Alliance-Support-Squad/coco-grad#34]
**Describe the bug**
When a message card has a word exceeding some finite character count, the page extends further left and becomes horizontally scrollable

**To Reproduce**
1. add message AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA in database
2. run backend and frontend
3. Scroll down to messages

**Expected behavior**
Messages should not cause horizontal scrolling

**Screenshots**
![image](https://user-images.githubusercontent.com/38551592/123730131-de148b80-d84a-11eb-974f-7e669169a398.png)

**Desktop (please complete the following information):**
 - OS: Fedora 34
 - Browser firefox
 - Version 89.0.2

**Additional context**
If it's my fault, I will git-blame-someone-else

**Comment by zapplecat** [comment]
I'm still able to scroll horizontally in responsive view, but I don't think that's what this PR is intending to fix.
![image](https://user-images.githubusercontent.com/6146988/123874138-44f27d00-d8fd-11eb-8508-9b5c86490df0.png)
