### ISSUE TITLE
Webkit viewport clips content at low horizontal resolutions

### ISSUE THREAD

**Issue by DuongTyler** [Manotomo-Alliance-Support-Squad/coco-grad#49]
**Describe the bug**
Webkit browsers overflow at low horizontal width viewports

**To Reproduce**
1. Install the Epiphany browser on Linux from flatpak, or get a mac/iphone with safari
2. change the viewport width to a super small phone resolution
3. Go to projects section

**Expected behavior**
The text should not flow off the screen

**Screenshots**
![image](https://user-images.githubusercontent.com/38551592/124232692-da8d3880-dac6-11eb-9691-1c35a00dc399.png)

**Desktop (please complete the following information):**
 - OS: Fedora 34
 - Browser: Epiphany
 - Version: 40.2

**Smartphone (please complete the following information):**
 - Device: iPhone 10
 - OS: Latest
 - Browser: Safari
 - Version: Latest

**Comment by Nephren68** [comment]
seems like it happens in Firefox and Chrome too, so...
![Firefox](https://user-images.githubusercontent.com/65450159/124359442-9c734e80-dc57-11eb-9285-7d9165b7a443.png)
![Chrome](https://user-images.githubusercontent.com/65450159/124359445-a006d580-dc57-11eb-807c-cc264dcfa4fb.png)
